# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and push oci image to ghcr.io
      run: |
        # new login with new container registry url and PAT
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        # new container registry urls added
        # docker pull ghcr.io//longwuyuan/spring:latest
        docker build . --tag ghcr.io/longwuyuan/spring:$GITHUB_SHA --cache-from ghcr.io/github/longwuyuan/spring:latest
        docker push ghcr.io/longwuyuan/spring:$GITHUB_SHA
